docs(awell-orchestration): add docs for scheduling tracks
awell-health/developer-hub pull request #145
Opened 2023-10-03 09:20 UTC by rahulkeerthi

Changes:
- get scheduled tracks
- unschedule tracks
- schedule track

2023-10-04 07:41 UTC, nckhell requested changes
You will have to add the pages to the menu in `/src/config/menus/awell-orchestration/apiMenu.ts`.

2023-10-04 07:41 UTC, nckhell commented on content/awell-orchestration/api-reference/mutations/schedule-track.mdx
> +description: Schedule a track in a patient care flow (pathway)
As long as we don't have a V2 of our API that adopts "care flow", I prefer we use pathway consistently in the documentation.

```suggestion
description: Schedule a track in a patient pathway
```

2023-10-04 07:41 UTC, nckhell commented on content/awell-orchestration/api-reference/mutations/schedule-track.mdx
> +The `pathway_id` is the id of the patient care flow (pathway) for which you want to stop a track. The `track_id` is the id of the track that you want to stop.
Link to the relevant sources/queries on how to get the `pathway_id` and the `track_id`.

2023-10-04 07:41 UTC, nckhell commented on content/awell-orchestration/api-reference/mutations/schedule-track.mdx
> +    "cancel_any_scheduled": true // optional, defaults to false
Explain separately what `cancel_any_scheduled` does, ideally including an example.

2023-10-04 07:41 UTC, nckhell commented on content/awell-orchestration/api-reference/mutations/unschedule-tracks.mdx
> +description: Unschedule tracks in a patient care flow (pathway)
```suggestion
description: Unschedule tracks in a patient pathway
```

2023-10-04 07:41 UTC, nckhell commented on content/awell-orchestration/api-reference/mutations/unschedule-tracks.mdx
> +```
The documentation doesn't match the input example:
- No `pathway_id` input
- No `track_id` but `ids` which is an array instead of a string

2023-10-04 07:41 UTC, nckhell commented on content/awell-orchestration/api-reference/mutations/unschedule-tracks.mdx
> +      "unscheduled_ids": ["{{SCHEDULED_TRACK_ID}}"] // array of ids that were successfully unscheduled
Unnecessary comment, field name is verbose enough

```suggestion
      "unscheduled_ids": ["{{SCHEDULED_TRACK_ID}}"]
```

2023-10-04 07:41 UTC, nckhell commented on content/awell-orchestration/api-reference/queries/get-scheduled-tracks.mdx
> +      id # unique id of the scheduled track, can be used to unschedule the track
```suggestion
      id # can be used to unschedule the track
```

2023-10-05 10:12 UTC, rahulkeerthi commented
@nckhell thanks for the feedback, I've made changes, let me know if the cancel_any_scheduled explanation is clear enough

2023-10-05 11:14 UTC, merged